[package]
name = "hw9q1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "filecreator"
path = "src/filecreator.rs" 

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"